# Generated by Django 3.2 on 2021-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionname', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('questions_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
