# Generated by Django 3.2 on 2021-05-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBanglaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choic', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=1)),
                ('question_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoBanglaApp.question')),
            ],
        ),
    ]
