# Generated by Django 3.2 on 2021-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBanglaApp', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userprofile',
            field=models.FileField(upload_to='profile'),
        ),
    ]
